### ISSUE TITLE
Large datasets. 

### ISSUE THREAD

**Issue by deepu** [tekartik/sembast_sqflite#2]
Hey, I love sembast and I am using it for small DBs <10MB for some iOS apps. 

Currently I have a requirement where might have to store 50-80 MB of data. However loading everything into memory at startup might be an issue. 

I stumbled on to this project (sembast on top of sqlfite) , 
1) does this project allow us more leeway in terms of the size of data that sembast will be good for ? 
2) will it be possible to lazy load partial data on start-up ?

**Comment by alextekartik** [comment]
Sorry I missed this issue. As a short response, no, this project only replace the storage format (sqlite database instead of text file). However, the data is still loaded in memory when opening the database.

Alternate native solutions would be sqlite on mobile/desktop and indexed_db on the web.
