### ISSUE TITLE
Error: type 'Null' is not a subtype of type 'int' in type cast

### ISSUE THREAD

**Issue by source-creator** [tekartik/sembast_sqflite#25]
Using the following
```
sembast: 3.7.1
sembast_sqflite: 2.2.0
Flutter: 3.19.6
Platform: Android 
```

On our app start, we are getting the following error.

It happens directly after calling `sqfFactory.openDatabase(...)`, when we initialise the database.  It mostly works fine, but I am not sure what happens for it to get to this state, so I haven't been able to reproduce the bug to see what is causing it.

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: type 'Null' is not a subtype of type 'int' in type cast
 at JdbDatabaseSqflite._encodedEntryFromCursor(jdb_database_sqflite.dart:32)
 at JdbDatabaseSqflite._entryFromCursorSync(jdb_database_sqflite.dart:53)
 at JdbDatabaseSqflite.entries.<fn>(jdb_database_sqflite.dart:88)
```

```
import 'package:sembast/sembast.dart';
import 'package:sembast_sqflite/sembast_sqflite.dart';
import 'package:sqflite/sqflite.dart' as sqflite;
...
final sqfFactory = getDatabaseFactorySqflite(sqflite.databaseFactory);
final Database database = await sqfFactory.openDatabase(
  filename,
  version: 1,
  mode: DatabaseMode.neverFails,
);
```

When looking at the source, it appears as though the contents of the entry table's id column are null.
I tried inserting null into the table manually, but the auto increment id won't let me do that.

1. Is this the correct approach to try and artificially reproduce this?
2. What do you think could be causing this?
3. What can I do to make sure the data is getting flushed to disk?

**Comment by alextekartik** [comment]
Thanks for the report. Puzzling indeed as the id cannot be null here. And like you say we cannot even reproduce it using the same database schema. I will add a where constraint in the query to make sure it is never null on load.

> 1. Is this the correct approach to try and artificially reproduce this?

To reproduce it i will likely create a database with a different schema without autoincrement id to allow inserting null.

> 2. What do you think could be causing this?

I really don't understand why such thing could be happening
Are you able to grab a copy of your failing database (to see whether indeed some id are null)

I'm puzzled by what could cause the issue.

> 3. What can I do to make sure the data is getting flushed to disk?

We rely here completely on SQLite behavior. Behavior will differ If [WAL](https://www.sqlite.org/wal.html) is enabled or not. Currently I don't let user override SQL opening mechanism (i.e. onUpgrade to configure SQL database do enable disable WAL). When a sembast transaction/write terminates, the data has been written in sqlite

**Comment by alextekartik** [comment]
You can look at my [commit](https://github.com/tekartik/sembast_sqflite/commit/4626a06c9d50178e3efbb0b2d58cd6a90965d925) on how I reproduced the issue (really tricky). It definitely should not happen but a simple modification makes sure it does not happen. You can try updating to 2.2.0+1

**Comment by alextekartik** [comment]
I'm also aware of an important issue on Android is that big cursors tends to create map with null values. So one solution is to tweak the page load size (i.e. how many rows are loaded at once during open). See here:
https://github.com/tekartik/sembast_sqflite/blob/master/sembast_sqflite/doc/setup_sqflite.md#options

By default rows are loaded by 1000, you can tweak this value using something like:

```
sqfFactory.sqfliteImportPageSize = 100;
```

That should prevent such issue on Android. I don't know how is your data and how big are your records (but I recommend keeping it low, see https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/usage_recommendations.md)

The workaround I did in my previous would actually hide this issue so I wonder if I should revert it (i.e. do we prefer a crash or loosing data...)

**Comment by source-creator** [comment]
@alextekartik Thank you very much for the speedy and informative reply, and also the fix!

Would reducing the default rows to 100 affect functionality of the app, or is it a performance thing?

The Android version it was happening on was 7.1.1.  I am wondering if there could be an IO issue in the old Android version?

I see in your usage you recommend using transactions for bulk ops.
I assume it is also important to await all write operations?

**Comment by alextekartik** [comment]
> Would reducing the default rows to 100 affect functionality of the app, or is it a performance thing?

It is only for performance, sembast loads all the data during open so indeed it is faster to have fewer SQL queries (loading by 100 would require 10 times morre queries than loading by 1000)

> The Android version it was happening on was 7.1.1. I am wondering if there could be an IO issue in the old Android version?

The issue with could likely be this (https://github.com/tekartik/sqflite/issues/373) I could not reproduce on newer Android version. It is not an IO issue but some limitation with the size of a cursor.

> I see in your usage you recommend using transactions for bulk ops.
> I assume it is also important to await all write operations?

Yes for consistency (and speed) use transaction. And yes properly await any action in a transaction. I personally properly await all write operation to know that indeed the data is saved at this point.

**Comment by source-creator** [comment]
Hi @alextekartik, we managed to somehow replicate the issue on a local device.  These are the errors proceeding the stacktrace and crash:
![db corrupt](https://github.com/tekartik/sembast_sqflite/assets/11390034/1ede1721-11e3-41a3-801f-332585518e18)

**Comment by source-creator** [comment]
The screenshot is with the update: `sembast_sqflite: 2.2.0+1`

**Comment by alextekartik** [comment]
Do you have access and can you share your database? It seems that it is trying to allocate too much memory, are your record big ? I know that on Android it would definitely fail if a record is bigger than 1MB. Have you tried setting a lower:

```
sqfFactory.sqfliteImportPageSize = 100;
```

Until it succeeds (i.e. if it fails will 100, try with 10 then 5, then...)

**Comment by source-creator** [comment]
Unfortunately I can't share the data.

There aren't many records in the database, 40 total.

I can confirm that 2 records are large.
The largest row is 2.56MB, the 2nd largest row is 972kB

I had already set page size to 100 as per your recommendation - but having less than 100 records I don't think this would make a difference.

We are going to try deleting the large record, and see if it still fails to load the data, on Android 7.1.1

**Comment by alextekartik** [comment]
> The largest row is 2.56MB, the 2nd largest row is 972kB

Ouch that's likely the issue.

> but having less than 100 records I don't think this would make a difference.

It would definitely make a difference as the issue is in SQLite itself. Can you try with 1 (yes sorry, just to be sure). If it fails with 1, one solution would be to try to sqflite_common_ffi along with sqlite3_flutter_libs to use a different SQL stack (see https://github.com/tekartik/sqflite/blob/master/sqflite_common_ffi/doc/using_ffi_instead_of_sqflite.md), it is just a change in the setup (some initialization code)

**Comment by alextekartik** [comment]
Also you should consider putting big blob in files and only store a reference to the file in sembast.
